version: "3.8"
services:
    mysql:
        container_name: mysql
        ports: 
            - 4306:3306
        environment:
            - MYSQL_DATABASE=projecttemplate
            - MYSQL_ROOT_PASSWORD=test
        volumes:
            - ./Database/schema/:/docker-entrypoint-initdb.d/
        image: mysql:5.6